#!/bin/sh

host=$1
user=$2
cluster=$3
path=$4

if [ $# -lt 3 ];then

	echo "Usage: $0 <PrismCentral ip> <AD login> <Karbon cluster name>"
	exit 1

fi

karbonctl login --pc-ip "$host" --pc-username "$user"

if [ -n "$path" ];then

	karbonctl cluster kubeconfig --cluster-name "$cluster" > "$path"

else

	karbonctl cluster kubeconfig --cluster-name "$cluster"

fi

